_wandb:
    value:
        cli_version: 0.21.1
        e:
            2ahxq3nsumxdbzjlrjezmbmo5rqeev1s:
                args:
                    - --config
                    - configs/base.yaml
                    - --use_wandb
                    - --dataset-type
                    - pickle
                codePath: scripts/train.py
                codePathLocal: scripts/train.py
                cpu_count: 30
                cpu_count_logical: 30
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "532608356352"
                        used: "38560518144"
                email: ridhib2422@gmail.com
                executable: /usr/bin/python
                git:
                    commit: 9d139d2e607dc547e9ea067441068ad0a9716729
                    remote: https://github.com/bendemonium/babylm-poincare-structformer.git
                gpu: NVIDIA A100-SXM4-40GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-4eda7bea-eac7-bd55-ab52-49648214a99c
                host: 132-226-106-78
                memory:
                    total: "232205705216"
                os: Linux-6.8.0-60-generic-x86_64-with-glibc2.35
                program: /home/ubuntu/babylm-poincare-structformer/scripts/train.py
                python: CPython 3.10.12
                root: /home/ubuntu/babylm-poincare-structformer
                startedAt: "2025-08-08T03:41:12.006081Z"
                writerId: 2ahxq3nsumxdbzjlrjezmbmo5rqeev1s
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 11
                - 12
                - 45
                - 49
                - 51
                - 53
            "2":
                - 1
                - 5
                - 11
                - 12
                - 45
                - 49
                - 51
                - 53
            "3":
                - 13
                - 16
            "4": 3.10.12
            "5": 0.21.1
            "6": 4.55.0
            "12": 0.21.1
            "13": linux-x86_64
batch_size:
    value: 128
c:
    value: 1
hidden_dim:
    value: 256
learning_rate:
    value: 0.0001
num_epochs:
    value: 5
num_heads:
    value: 8
num_layers:
    value: 4
seed:
    value: 42
seq_length:
    value: 128
train_tokenized_file:
    value: train_tokenized.pkl
train_tokenized_repo:
    value: bendemonium/babylm25_bpe_tokens
val_tokenized_file:
    value: null
val_tokenized_repo:
    value: dev_tokenized.pkl
vocab_name:
    value: gpt2
wandb_project:
    value: structformer-flax
wandb_run_name:
    value: run-001
