_wandb:
    value:
        cli_version: 0.21.1
        e:
            4hx5agz7acmkdseipxuwzzhkkeio5zy6:
                args:
                    - --config
                    - configs/base.yaml
                    - --dry-run
                codePath: scripts/train.py
                codePathLocal: scripts/train.py
                cpu_count: 30
                cpu_count_logical: 30
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "532608356352"
                        used: "47941255168"
                email: ridhib2422@gmail.com
                executable: /home/ubuntu/babylm-poincare-structformer/bb-env/bin/python
                git:
                    commit: 5124ec8a2638b58acfaf973c675f95632a336e51
                    remote: https://github.com/bendemonium/babylm-poincare-structformer.git
                gpu: NVIDIA A100-PCIE-40GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-PCIE-40GB
                      uuid: GPU-9bb74477-329b-8f44-df4c-31a5202fbf2c
                host: 104-171-202-142
                memory:
                    total: "237490540544"
                os: Linux-6.8.0-60-generic-x86_64-with-glibc2.35
                program: /home/ubuntu/babylm-poincare-structformer/scripts/train.py
                python: CPython 3.10.12
                root: /home/ubuntu/babylm-poincare-structformer
                startedAt: "2025-08-10T04:32:46.487212Z"
                writerId: 4hx5agz7acmkdseipxuwzzhkkeio5zy6
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 11
                - 12
                - 45
                - 49
                - 51
            "2":
                - 1
                - 11
                - 12
                - 45
                - 49
                - 51
            "3":
                - 13
                - 61
            "4": 3.10.12
            "5": 0.21.1
            "6": 4.55.0
            "12": 0.21.1
            "13": linux-x86_64
