train_files: "data/train/*.train"
val_files: "data/dev/*.dev"
batch_size: 32
seq_length: 128
learning_rate: 0.0005
num_epochs: 3
vocab_name: "gpt2"
seed: 42
hidden_dim: 512
num_heads: 8
num_layers: 6
