train_files: "data/train/*.train"
val_files: "data/dev/*.dev"
batch_size: 32
seq_length: 128
learning_rate: 0.0003
num_epochs: 5
vocab_name: "gpt2"
seed: 123
hidden_dim: 768
num_heads: 12
num_layers: 12
